# Generated by Django 6.0.6 on 2026-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'transaction_type'], name='accounts_tr_date_aa5c26_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='accounts_tr_categor_1ba92e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method', 'date'], name='accounts_tr_payment_606097_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='accounts_tr_account_bdde70_idx'),
        ),
    ]
