# Generated by Django 6.0.6 on 2026-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_multi_tenant_isolation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
