# Generated by Django 6.0.6 on 2026-07-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sale_customer_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupRecord',
        ),
    ]
