# Generated by Django 6.0.6 on 2026-07-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_backuprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
