# Generated by Django on demand
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=255)),
                ('level', models.CharField(default='INFO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('last_backup_date', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_backup', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(default='default-device', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BackupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dirty', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='IDLE', max_length=50)),
                ('progress_message', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.BinaryField()),
                ('refresh_token', models.BinaryField()),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('token_uri', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
